/*
CONSULTA DATOS PAX
===============
SELECT CC.BIRTH_DT,CC.ASST_PH_NUM, CC.CON_ASST_NAME,CC.EMAIL_ADDR,CC.HOME_PH_NUM
FROM SIEBEL.S_CONTACT CC
WHERE 1=1
AND CC.X_IDEN_NUM ='32740573'
*/

UPDATE SIEBEL.S_CONTACT 
SET BIRTH_DT=''
,ASST_PH_NUM=''
, CON_ASST_NAME=''
,EMAIL_ADDR=''
,HOME_PH_NUM=''
WHERE 1=1
AND X_IDEN_NUM ='32740573'

/* CONSULTA PLAN DE PAGOS
    ==================

SELECT PP.EXPIRATION_DT,PP.ACCOUNT_NAME,PP.ACCOUNT_TYPE_CD,PP.X_UA_EMAIL_TIT_TARJETA, PP.X_UA_DOC_TIT_TARJETA
FROM SIEBEL.S_PAY_PLAN PP
WHERE 1=1
AND PP.ASSET_ID IN ( '1-D612Q2E','1-DGCATYU','1-DM2818M')
*/

UPDATE SIEBEL.S_PAY_PLAN
SET EXPIRATION_DT=''
,ACCOUNT_NAME=''
,ACCOUNT_TYPE_CD=''
,X_UA_EMAIL_TIT_TARJETA=''
, X_UA_DOC_TIT_TARJETA=''
WHERE 1=1
AND ASSET_ID IN ( '1-D612Q2E','1-DGCATYU','1-DM2818M')

/* CONSULTA COBRO
    ============
SELECT AXM.ATTRIB_47,AXM.X_UA_ATTRIB_24,AXM.X_UA_MAIL_LINK
FROM SIEBEL.S_ASSET_XM AXM
WHERE 1=1
AND AXM.PAR_ROW_ID ='1-D9YQY80'
AND AXM.TYPE ='Validadores Cobro'
*/

UPDATE SIEBEL.S_ASSET_XM 
SET ATTRIB_47='',
X_UA_ATTRIB_24='',
X_UA_MAIL_LINK=''
WHERE 1=1
AND PAR_ROW_ID ='1-D9YQY80'
AND TYPE ='Validadores Cobro'