SELECT COUNT(1) "PROSPECTOS",PC.FST_NAME,PC.LAST_NAME,PC.CELL_PH_NUM,PC.HOME_PH_NUM,PC.EMAIL_ADDR--,PC.PROMO_TO_CON_ID
--,TO_CHAR (PC.CREATED,'MMYYYY') "MES"
FROM SIEBEL.S_PRSP_CONTACT PC
LEFT JOIN SIEBEL.S_LEAD L ON PC.ROW_ID = L.PRSP_CON_ID
WHERE 1=1
AND PC.EMAIL_ADDR IN ('integrations@netactica.com','sistemas1@juantoselli.com','sistemas@juantoselli.com')
--AND PC.LAST_NAME ='86 - 100'
--AND PC.FST_NAME ='Cotizacion'
--AND PC.CREATED < '05/05/2022'
AND PC.PROMO_TO_CON_ID IS NULL
--AND L.LEAD_NUM IS NULL
GROUP BY PC.FST_NAME,PC.LAST_NAME,PC.CELL_PH_NUM,PC.HOME_PH_NUM ,PC.EMAIL_ADDR--,PC.PROMO_TO_CON_ID
--,TO_CHAR (PC.CREATED,'MMYYYY')
HAVING COUNT(1) >1
--CANT = 1280079