/*
    PUEDO ACTUALIZAR POR SIMULADOR DE BS UPDATE BC
*/


SELECT A.ROW_ID "Voucher Id",  CONCAT(CONCAT('[Asset Id] = ''',A.ROW_ID),'''') "SearchExpr",
A.ASSET_NUM "Voucher",APC.PROD_ID "Prod Id",
--AX.ATTRIB_42 NRO_CONTROL,
PI.NAME "Producto", V.VOD_NAME "Clase", 
APC.X_UA_CLASE_ID "Clase Id Voucher",
VV1.VOD_ID "Clase Id 2",
APC.X_UA_VERSION_CLASE_ID "Version Clase Id Voucher",
VV1.VER_ID "Version Clase Id 2",
VV.VER_NUM "Version 1",VV1.VER_NUM "Version 2",
VV1.START_DT "Fecha Inicio"
FROM SIEBEL.S_APPLD_CVRG APC
LEFT JOIN SIEBEL.S_PROD_INT PI ON APC.PROD_ID = PI.ROW_ID
LEFT JOIN SIEBEL.S_ASSET A ON APC.ASSET_ID = A.ROW_ID
LEFT JOIN SIEBEL.S_VOD_VER VV ON VV.ROW_ID = APC.X_UA_VERSION_CLASE_ID
--LEFT JOIN SIEBEL.S_ASSET_X AX ON APC.ASSET_ID = AX.PAR_ROW_ID
LEFT JOIN SIEBEL.S_VOD V ON V.ROW_ID = APC.X_UA_CLASE_ID
LEFT JOIN SIEBEL.S_VOD_VER VV1 ON VV1.VOD_ID = V.ROW_ID
WHERE 1=1
AND A.ASSET_NUM IN('T012208556')
--AND V1.VOD_NAME = 'BRASIL - CVC6005 / 00'
--AND APC.PROD_ID = '1-CPDMD39'
--AND APC.CREATED > '01/01/2016' 
--and VV.VER_NUM <>VV1.VER_NUM
--and VV1.START_DT is not null
--AND VV1.CURR_VER_FLG ='N'
--AND PI.NAME = 'CVC7318'
--AND APC.X_UA_CLASE_ID ='1-AUMB6TG'
--AND VV1.RELEASED_FLG = 'Y'
--AND VV1.VER_NUM IN (6)


/*  ACTUALIZACIÓN DE VERSION DE LA CLASE EN EL VOUCHER
UPDATE SIEBEL.S_APPLD_CVRG
SET --PROD_ID='1-6AV1Q7',
X_UA_VERSION_CLASE_ID='1-D04IJDH'
--,X_UA_CLASE_ID='1-CSJY13N'
WHERE 1=1
--AND PROD_ID= '1-CPDMD39'
--AND X_UA_CLASE_ID ='1-D04IJDH'
AND ASSET_ID IN (SELECT ROW_ID FROM SIEBEL.S_ASSET A WHERE ASSET_NUM in   ('T011483482')
)   
*/

/*      CONSULTA VERSION DE PRODUCTO PARA COLUMNA  X_UA_VERSION_CLASE_ID

SELECT VV.ROW_ID,  VV.VER_NUM,VV.*
FROM SIEBEL.S_VOD_VER VV WHERE ROW_ID IN ('1-92N940N' )--,'1-92MJMT2','1-92N940N','1-90GTIRN')
*/

/*      CONSULTA CLASE DE PRODUCTO PARA COLUMNA X_UA_CLASE_ID
SELECT ROW_ID,VOD_NAME
FROM SIEBEL.S_VOD V 
WHERE ROW_ID IN ('1-92MJMO3','1-32GMCV')
*/

