DROP VIEW UABIEXT.XX_BI_CASOS;

/* Formatted on 29/6/2022 14:31:58 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW UABIEXT.XX_BI_CASOS
(
   NUM_CASO,
   FECHA_CREACION,
   VOUCHER_COBERTURA,
   TIPO_CASO,
   ESTADO,
   SUBESTADO,
   CIUDAD,
   PROVINCIA,
   PAIS,
   MOTIVO_ATENCION,
   COMPLEJIDAD,
   SEGUIMIENTO,
   PRODUCTO,
   EDAD_CASO,
   CLIENTE,
   CARGA_MANUAL,
   BENEFICIARIO,
   CATEGORIA,
   SINTOMA,
   FECHA_NOVEDAD,
   PUESTO_CREADOR_CASO,
   GRUPO_ASIGNADO,
   TIPO_SERVICIO,
   ORG_EMISORA,
   TIPO_DOCUMENTO,
   NRO_DOCUMENTO,
   EMAIL_CONTACTO,
   TEL_CONTACTO,
   ESPECIALIDAD,
   DERIVACION_DIRECTA,
   SINTOMA_SECUNDARIO,
   SINTOMA_TERCIARIO,
   URGENCIA,
   CREADOR,
   TIPO_ASISTENCIA_ORIGINAL
)
AS
   SELECT DISTINCT
          T1.SR_NUM AS NUM_CASO,
          TO_CHAR (T1.ACT_OPEN_DT, 'YYYY-MM-DD') AS FECHA_CREACION, -- A.SCHILLIZZI 05/09/2018 SE CAMBIO CAMPO CREACION CASO: T1.CREATED
          T1.TT_TYPE_CD AS VOUCHER_COBERTURA,
          T1.SR_AREA AS TIPO_CASO,
          T1.SR_STAT_ID AS ESTADO,
          T1.SR_SUB_STAT_ID AS SUBESTADO,
          T1.SOURCE_TYP_CD AS CIUDAD,
          T1.SR_SUBTYPE_CD AS PROVINCIA,
          T1.SR_TYPE_CD AS PAIS,
          T1.SR_SUB_AREA AS MOTIVO_ATENCION,
          T2.ATTRIB_38 AS COMPLEJIDAD,
          T2.UA_SEG_FLAG AS SEGUIMIENTO,
          T2.ATTRIB_37 AS PRODUCTO,
          T2.X_EDAD_CASO AS EDAD_CASO,
          T3.NAME AS CLIENTE,
          T4.X_UA_CARGA_MANUAL AS CARGA_MANUAL,
          REPLACE (T1.ALT_CONTACT_NAME, '|', ' ') AS BENEFICIARIO,
          T1.SR_CATEGORY_CD AS CATEGORIA,
          T1.X_SINTOMA SINTOMA,
          TO_CHAR (T1.LAST_UPD, 'YYYY-MM-DD') FECHA_NOVEDAD,
          UPPER (SP.NAME) PUESTO_CREADOR_CASO,
          T6.ATTRIB_45 GRUPO_ASIGNADO,
          DECODE (
             T1.TT_TYPE_CD,
             -- Es cobertura, no es un voucher
             T1.ASSET_ID, (SELECT S_PROD_INT_X.ATTRIB_04
                             FROM SIEBEL.S_PROD_INT_X,
                                  SIEBEL.S_ASSET_ITEM,
                                  SIEBEL.S_ASSET
                            WHERE S_PROD_INT_X.PAR_ROW_ID =
                                     S_ASSET_ITEM.PROD_ID
                                  AND S_ASSET_ITEM.ASSET_ID = S_ASSET.ROW_ID
                                  AND S_ASSET.ROW_ID = T1.ASSET_ID
                                  AND ROWNUM = 1),
             -- Es un voucher
             (SELECT S_PROD_INT_X.ATTRIB_04
                FROM SIEBEL.S_PROD_INT_X, SIEBEL.S_APPLD_CVRG, SIEBEL.S_ASSET
               WHERE     S_PROD_INT_X.PAR_ROW_ID = S_APPLD_CVRG.PROD_ID
                     AND S_APPLD_CVRG.ROW_ID = S_ASSET.PROD_ID
                     AND S_ASSET.ROW_ID = T1.ASSET_ID))
             TIPO_SERVICIO,
          T8.NAME ORG_EMISORA,
          T2.X_IDEN_TYPE_CD TIPO_DOCUMENTO,
          T2.X_IDEN_NUM NRO_DOCUMENTO,
          T2.X_MAIL_BENEFICIARIO,               -- 21/01/2020 - MAT - REQ 5873
          T2.X_TEL_RESIDENCIA,                  -- 21/01/2020 - MAT - REQ 5873
          T1.X_ESPECIALIDAD,                    -- 23/06/2021 - MAT - REQ 6025
          T1.X_DERIVACION_DIRECTA,              -- 23/06/2021 - MAT - REQ 6025
          t1.x_sintoma_secundario,              -- 23/06/2021 - MAT - REQ 6025
          t1.x_sintoma_terciario,               -- 23/06/2021 - MAT - REQ 6025
          t1.sr_prio_cd AS URGENCIA,            -- 23/06/2021 - MAT - REQ 6025
          T9.LOGIN AS CREADOR  -- 01/09/2021 - MAT -  REQ 6224 Usuario creador
          ,T1.X_TIPO_ASISTENCIA_ORIGINAL AS TIPO_ASISTENCIA_ORIGINAL -- 30/06/2022 - MAT - REQ 6651
     FROM SIEBEL.S_SRV_REQ T1,
          SIEBEL.S_SRV_REQ_X T2,
          SIEBEL.S_ORG_EXT T3,
          SIEBEL.S_ASSET_CON T4,
          SIEBEL.S_CONTACT SC,                     -- NOMBRE PROPIETATRIO CASO
          SIEBEL.S_POSTN SP,                        -- PUESTO PROPIETARIO CASO
          SIEBEL.S_USER USC,                           -- PROPIETARIO DEL CASO
          SIEBEL.S_SRV_REQ_X T6,
          SIEBEL.S_ASSET T7,
          SIEBEL.S_ORG_EXT T8,
          SIEBEL.S_USER T9     -- 01/09/2021 - MAT -  REQ 6224 Usuario creador
    WHERE     1 = 1
          AND T7.BU_ID = T8.ROW_ID(+)
          AND T1.ASSET_ID = T7.ROW_ID(+)
          AND T1.ROW_ID = T6.PAR_ROW_ID
          AND SC.PR_HELD_POSTN_ID = SP.ROW_ID(+)
          AND USC.ROW_ID = SC.ROW_ID(+)             -- NOMBRE PROPIETARIO CASO
          AND T1.OWNER_EMP_ID = USC.PAR_ROW_ID(+)      -- PROPIETARIO DEL CASO
          AND T4.CONTACT_ID(+) = T1.CST_CON_ID
          AND T4.ASSET_ID(+) = T1.ASSET_ID
          AND T3.PAR_ROW_ID = T1.CST_OU_ID
          AND T1.ROW_ID = T2.PAR_ROW_ID
          AND T1.CREATED_BY = T9.ROW_ID -- 01/09/2021 - MAT -  REQ 6224 Usuario creador
          AND T1.SR_CATEGORY_CD IN ('Caso', 'Casos Prestadores');


GRANT SELECT ON UABIEXT.XX_BI_CASOS TO CONSULTA_ROLE;