DROP VIEW UABIEXT.XX_BI_PRESTACIONES;

/* Formatted on 20/4/2022 09:37:03 (QP5 v5.163.1008.3004) */
CREATE OR REPLACE FORCE VIEW UABIEXT.XX_BI_PRESTACIONES
(
   NRO_PRESTACION,
   NRO_CASO,
   FECHA_CREACION,
   FECHA_CREACION_CASO,
   ESTADO,
   SUBESTADO,
   TIPO_PRESTACION,
   NOMBRE_PRESTADOR,
   TIPO_ASISTENCIA,
   PAIS_PRESTACION,
   PROVINCIA_PRESTACION,
   CIUDAD_PRESTACION,
   MONEDA_AUDITORIA,
   PRODUCTO_VENTA,
   RAZON_SOCIAL_AUDITORIA,
   REFACTURACION,
   MONTO_REFACTURAR,
   A_QUIEN_REFACTURAR,
   REFACTURAR_CLIENTE,
   PRODUCTO_PRESTACIONAL,
   APLICA_FRANQUICIA,
   COPAGO,
   RAZON_SOCIAL_VENTA,
   CLIENTE_FACTURACION,
   CIA_SEGURO,
   CATEGORIA,
   FECHA_NOVEDAD,
   NRO_POLIZA,
   COBERTURA_INF
)
AS
   SELECT DISTINCT
          T1.SR_NUM AS NRO_PRESTACION, 
          T3.ATTRIB_06 AS NRO_CASO,
          TO_CHAR (T1.CREATED, 'YYYY-MM-DD') AS FECHA_CREACION,
          TO_CHAR (T2.CREATED, 'YYYY-MM-DD') AS FECHA_CREACION_CASO,
          T1.SR_STAT_ID AS ESTADO,
          T1.SR_SUB_STAT_ID AS SUBESTADO,
          T1.SR_AREA AS TIPO_PRESTACION,
          T1.TEMP_PH_NUM AS NOMBRE_PRESTADOR,
          T1.SR_SUB_AREA AS TIPO_ASISTENCIA,
          T1.SR_TYPE_CD AS PAIS_PRESTACION,
          T1.SR_SUBTYPE_CD AS PROVINCIA_PRESTACION,
          T1.SOURCE_TYP_CD AS CIUDAD_PRESTACION,
          T3.X_MONEDA_AUDIT AS MONEDA_AUDITORIA,
          T4.ATTRIB_37 AS PRODUCTO_VENTA,
          T3.ATTRIB_02 AS RAZON_SOCIAL_AUDITORIA,
          T3.ATTRIB_09 AS REFACTURACION,
          REPLACE (T3.ATTRIB_22, ',', '.') AS MONTO_REFACTURAR,
          T3.ATTRIB_37 AS A_QUIEN_REFACTURAR,
          T3.ATTRIB_44 AS REFACTURAR_CLIENTE,
          T3.ATTRIB_39 AS PRODUCTO_PRESTACIONAL,
          T3.ATTRIB_11 AS APLICA_FRANQUICIA,
          T3.X_COPAGO_RATE AS COPAGO,
          T5.CHANNEL_TYPE AS RAZON_SOCIAL_VENTA,
          T6.NAME AS CLIENTE_FACTURACION,
          T7.X_CIA_SEGURO AS CIA_SEGURO,
          T1.SR_CATEGORY_CD AS CATEGORIA,
          TO_CHAR (T1.LAST_UPD, 'YYYY-MM-DD') FECHA_NOVEDAD,
          T10.ATTRIB_03 NRO_POLIZA,
          DECODE (T12.TGT_REGION_CD,
                  'Nacional', T13.LOW,
                  'Internacional', T13.HIGH)
             COBERTURA_INF
     FROM SIEBEL.S_SRV_REQ T1,
          SIEBEL.S_SRV_REQ T2,
          SIEBEL.S_SRV_REQ_X T3,
          SIEBEL.S_SRV_REQ_X T4,
          SIEBEL.S_ORG_EXT T5,
          SIEBEL.S_ORG_EXT T6,
          SIEBEL.S_ASSET_X T7,
          SIEBEL.S_ASSET_CON T10,
          SIEBEL.S_APPLD_CVRG T11,
          SIEBEL.S_PROD_INT T12,
          SIEBEL.S_LST_OF_VAL T13
   --      ,SIEBEL.S_WORKSPACE T14 -- SOLO PARA QA
    WHERE     T1.SR_CATEGORY_CD = 'Autorización'
          AND T2.ROW_ID = T1.PAR_SR_ID
          AND T1.ROW_ID = T3.PAR_ROW_ID
          AND T4.PAR_ROW_ID = T1.PAR_SR_ID
          AND T5.ROW_ID = T6.PR_BL_OU_ID
          AND T6.PAR_ROW_ID(+) = T1.CST_OU_ID
          AND T7.ROW_ID(+) = T1.ASSET_ID
          AND T1.CST_CON_ID = T10.CONTACT_ID(+)
          AND T1.X_ASSET_ID_CASO = T10.ASSET_ID(+)
          AND T1.ASSET_ID = T7.ROW_ID(+)
          AND T7.ROW_ID = T11.ASSET_ID(+)
          AND T11.PROD_ID = T12.ROW_ID(+)
          AND T1.SR_SUB_AREA = T13.VAL(+)
 --        AND T13.WS_ID = T14.ROW_ID(+)      -- SOLO PARA QA
 --        AND T14.DEV_WS_NAME = T14.NAME -- SOLO PARA QA
          AND (T13.TYPE = 'SR_AREA')  
          AND (T13.WS_MAX_VER = 10000)      -- Se agrega por mail lunes 18/4/2022 16:00  RE: Consulta de Casos / Prestaciones - SIEBEL   
          --AND (T13.ACTIVE_FLG = 'Y')              -- Se inactiva por mail lunes 18/4/2022 16:00  RE: Consulta de Casos / Prestaciones - SIEBEL         
   UNION ALL
   SELECT DISTINCT T1.SR_NUM AS NRO_PRESTACION,
                   T2.ATTRIB_06 AS NRO_CASO,
                   TO_CHAR (T1.CREATED, 'YYYY-MM-DD') AS FECHA_CREACION,
                   TO_CHAR (T6.CREATED, 'YYYY-MM-DD') AS FECHA_CREACION_CASO,
                   T1.SR_STAT_ID AS ESTADO,
                   T1.SR_SUB_STAT_ID AS SUBESTADO,
                   T1.SR_AREA AS TIPO_PRESTACION,
                   T1.TEMP_PH_NUM AS NOMBRE_PRESTADOR,
                   T1.SR_SUB_AREA AS TIPO_ASISTENCIA,
                   T1.SR_TYPE_CD AS PAIS_PRESTACION,
                   T1.SR_SUBTYPE_CD AS PROVINCIA_PRESTACION,
                   T1.SOURCE_TYP_CD AS CIUDAD_PRESTACION,
                   T2.X_MONEDA_AUDIT AS MONEDA_AUDITORIA,
                   T7.ATTRIB_37 AS PRODUCTO_VENTA,
                   T2.ATTRIB_02 AS RAZON_SOCIAL_AUDITORIA,
                   T2.ATTRIB_09 AS REFACTURACION,
                   REPLACE (T2.ATTRIB_22, ',', '.') AS MONTO_REFACTURAR,
                   T2.ATTRIB_37 AS A_QUIEN_REFACTURAR,
                   T2.ATTRIB_44 AS REFACTURAR_CLIENTE,
                   T2.ATTRIB_39 AS PRODUCTO_PRESTACIONAL,
                   T2.ATTRIB_11 AS APLICA_FRANQUICIA,
                   T2.X_COPAGO_RATE AS COPAGO,
                   T8.CHANNEL_TYPE AS RAZON_SOCIAL_VENTA,
                   T3.NAME AS CLIENTE_FACTURACION,
                   '' AS CIA_SEGURO,
                   T1.SR_CATEGORY_CD AS CATEGORIA,
                   TO_CHAR (T1.LAST_UPD, 'YYYY-MM-DD') FECHA_NOVEDAD,
                   '' AS NRO_POLIZA,
                   '' AS COBERTURA_INF
     FROM SIEBEL.S_SRV_REQ T1,
          SIEBEL.S_SRV_REQ_X T2,
          SIEBEL.S_ORG_EXT T3,
          SIEBEL.S_ASSET_CON T4,
          SIEBEL.S_SYMPTOM T5,
          SIEBEL.S_SRV_REQ T6,
          SIEBEL.S_SRV_REQ_X T7,
          SIEBEL.S_ORG_EXT T8,
          SIEBEL.S_ORG_EXT T9
    WHERE     T1.SR_CATEGORY_CD = 'Reintegros'
          AND T1.ROW_ID = T2.PAR_ROW_ID
          AND T3.PAR_ROW_ID = T1.CST_OU_ID
          AND T4.ASSET_ID(+) = T1.ASSET_ID
          AND T4.CONTACT_ID(+) = T1.CST_CON_ID
          AND T5.ROW_ID(+) = T1.PR_SYMPTOM_CD
          AND T6.ROW_ID = T1.PAR_SR_ID
          AND T7.PAR_ROW_ID = T1.PAR_SR_ID
          AND T8.ROW_ID = T9.PR_BL_OU_ID
          AND T9.PAR_ROW_ID = T1.CST_OU_ID;


GRANT SELECT ON UABIEXT.XX_BI_PRESTACIONES TO CONSULTA_ROLE;
